const actions = {
    DISPLAY_LOADER: 'DISPLAY_LOADER',
    DISPLAY_ERROR: 'DISPLAY_ERROR',
    FETCH_WEATHER_SUCCESS: 'FETCH_WEATHER_SUCCESS',
    ADD_TO_HISTORY: 'ADD_TO_HISTORY',
    REMOVE_FROM_HISTORY: 'REMOVE_FROM_HISTORY',
    SET_WEATHER: 'SET_WEATHER'
};

export default actions;